### ISSUE TITLE
ParseError while trying sample code

### ISSUE THREAD

**Issue by milokmet** [tanaikech/FetchApp#2]
Hi I tried an example in readme file and I got this as response: { "error": { "errors": [ { "domain": "global", "reason": "parseError", "message": "Parse Error" } ], "code": 400

What should I do wrong? I just copy/paste your code. First I got error 403 insufficient privileges, but I created files with google app script. To authorize the application for write. But than I got code 400.

thanks

**Comment by tanaikech** [comment]
Thank you for your comment. Unfortunately, I couldn't understand about your situation from your comment. I apologize for this situation. So can you provide the detail information (flow and script) for completely replicating your situation? If there are some bugs, I would like to modify them.

**Comment by milokmet** [comment]
Hello. Here is the code I tried to use the function main 
```
function main() {
  var id = 'abcd';
  var fileBlob = DriveApp.getFileById(id).getBlob();
  
  var metadata = {
    name: "OCR-PDF-" + (new Date()).getYear(),
    mimeType: MimeType.GOOGLE_DOCS
  };
  
  var form = FetchApp.createFormData();
  form.append("metadata", Utilities.newBlob(JSON.stringify(metadata)));
  form.append("file", fileBlob);
  var url = "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart";
  
  var params = {
    method: "POST",
    headers: { Authorization: "Bearer " + ScriptApp.getOAuthToken() },
    body: form
    // muteHttpExceptions: true
  };
  
  var res = FetchApp.fetch(url, params);
  Logger.log(res);
}
```
And I got an exact error in slovak language:
```
Požiadavka zlyhala, pretože služba https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart vrátila kód 400. Skrátená odpoveď servera: { "error": { "errors": [ { "domain": "global", "reason": "parseError", "message": "Parse Error" } ], "code": 400, "messa... (ak chcete preskúmať celú odpoveď, použite možnosť muteHttpExceptions) (riadok 69, súbor Code, projekt FetchApp)
```

Translated: Request failed, because service https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart response code was 400. Response from server: { "error": { "errors": [ { "domain": "global", "reason": "parseError", "message": "Parse Error" } ], "code": 400, "messa...
line 69, file Code, project FetchAppp

I do not know how to debug code of FetchApp from a library, or how can I just copy the code to my project.

Thank you

**Comment by tanaikech** [comment]
Thank you for replying. From your replying, I think that I could correctly understand your situation.

## Modification point:
- For ``metadata``, please add the mimeType of ``application/json``.

So could you please modify as follows and try to run again?

## Modified script:
### From:
```javascript
form.append("metadata", Utilities.newBlob(JSON.stringify(metadata)));
```

### To:
```javascript
form.append("metadata", Utilities.newBlob(JSON.stringify(metadata), "application/json"));
```

If this was not the solution, I apologize.

**Comment by milokmet** [comment]
Great! How could I missed that? Thank you very much.

**Comment by tanaikech** [comment]
Welcome. I'm glad your issue was resolved.
